import mongoose from "mongoose";
const expenseSchema = new mongoose.Schema(
  {
    groupId: { type: mongoose.Schema.Types.ObjectId, ref: "Group", required: true, index: true },
    title: { type: String, required: true, trim: true },
    amountMinor: { type: Number, required: true, min: 1 },
    paidByParticipantId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Participant",
      required: true
    },
    // generated by split.js
    splitJson: { type: Object, required: true }
  },
  { timestamps: { createdAt: true, updatedAt: false }, versionKey: false }
);
expenseSchema.index({ groupId: 1, createdAt: -1 });
export const Expense = mongoose.model("Expense", expenseSchema);